// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0AVplzziy0C2_poTEKjtdzgyVKehURd8',
    appId: '1:77278129399:web:8a4ad1d6e610bd0de4b7f2',
    messagingSenderId: '77278129399',
    projectId: 'towerchallenge3008',
    authDomain: 'towerchallenge3008.firebaseapp.com',
    storageBucket: 'towerchallenge3008.firebasestorage.app',
    measurementId: 'G-22BP7QC6NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjP2l-IcgW_cvxT2aDh46R3VQ-uIqWvUY',
    appId: '1:77278129399:android:c91b80aa583dce71e4b7f2',
    messagingSenderId: '77278129399',
    projectId: 'towerchallenge3008',
    storageBucket: 'towerchallenge3008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwGcjn2Sszdugq4W8phl359Lz1EiMExHw',
    appId: '1:77278129399:ios:54d6f1bb7decb6d7e4b7f2',
    messagingSenderId: '77278129399',
    projectId: 'towerchallenge3008',
    storageBucket: 'towerchallenge3008.firebasestorage.app',
    iosBundleId: 'com.example.towerChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwGcjn2Sszdugq4W8phl359Lz1EiMExHw',
    appId: '1:77278129399:ios:54d6f1bb7decb6d7e4b7f2',
    messagingSenderId: '77278129399',
    projectId: 'towerchallenge3008',
    storageBucket: 'towerchallenge3008.firebasestorage.app',
    iosBundleId: 'com.example.towerChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0AVplzziy0C2_poTEKjtdzgyVKehURd8',
    appId: '1:77278129399:web:db49657ca4ce1085e4b7f2',
    messagingSenderId: '77278129399',
    projectId: 'towerchallenge3008',
    authDomain: 'towerchallenge3008.firebaseapp.com',
    storageBucket: 'towerchallenge3008.firebasestorage.app',
    measurementId: 'G-VLEMPM3KQQ',
  );
}
